const fs = require('fs');
const path = require('path');

let arabicData = null;

function loadArabicData() {
  if (arabicData) return arabicData;
  try {
    arabicData = JSON.parse(
      fs.readFileSync(path.join(__dirname, '..', 'data', 'ar', 'countries.json'), 'utf8')
    );
  } catch {
    arabicData = {};
  }
  return arabicData;
}

const continentMap = {
  'Africa': 'أفريقيا',
  'Asia': 'آسيا',
  'Europe': 'أوروبا',
  'North America': 'أمريكا الشمالية',
  'South America': 'أمريكا الجنوبية',
  'Antarctica': 'أنتاركتيكا',
  'Oceania': 'أوقيانوسيا',
  'Australia': 'أوقيانوسيا',
};

const climateMap = {
  'Arid': 'جاف',
  'Arid or semiarid': 'جاف أو شبه جاف',
  'Arid to semiarid': 'جاف إلى شبه جاف',
  'Cold': 'بارد',
  'Cold temperate': 'معتدل بارد',
  'Cold winters, cool summers': 'شتاء بارد وصيف معتدل',
  'Continental': 'قاري',
  'Cool': 'بارد',
  'Cool temperate': 'معتدل بارد',
  'Desert': 'صحراوي',
  'Desert climate': 'مناخ صحراوي',
  'Diverse': 'متنوع',
  'Dry continental to polar': 'قاري جاف إلى قطبي',
  'Dry desert': 'صحراوي جاف',
  'Dry, semiarid steppe': 'سهب جاف شبه جاف',
  'Equatorial': 'استوائي',
  'Extremely diverse': 'متنوع للغاية',
  'Generally arid to semiarid': 'جاف إلى شبه جاف بشكل عام',
  'Generally cool winters and mild summers': 'شتاء بارد وصيف معتدل بشكل عام',
  'Harsh, dry desert': 'صحراوي جاف قاس',
  'Highland': 'مرتفع',
  'Highland continental': 'قاري مرتفع',
  'Hot': 'حار',
  'Hot and dry': 'حار وجاف',
  'Hot desert': 'صحراوي حار',
  'Hot desert climate': 'مناخ صحراوي حار',
  'Hot summers and cold winters': 'صيف حار وشتاء بارد',
  'Hot with seasonal rainfall': 'حار مع أمطار موسمية',
  'Hot, dry desert': 'صحراوي حار جاف',
  'Humid continental': 'قاري رطب',
  'Humid subtropical': 'شبه استوائي رطب',
  'Marine west coast': 'ساحل غربي بحري',
  'Maritime': 'بحري',
  'Maritime temperate': 'معتدل بحري',
  'Maritime, wet, moderate winters': 'بحري رطب شتاء معتدل',
  'Mediterranean': 'متوسطي',
  'Mediterranean along coast': 'متوسطي على الساحل',
  'Mediterranean and continental': 'متوسطي وقاري',
  'Mediterranean climate': 'مناخ متوسطي',
  'Mediterranean climate on the coast': 'مناخ متوسطي على الساحل',
  'Midlatitude continental': 'قاري متوسط العرض',
  'Mild temperate': 'معتدل لطيف',
  'Moderate': 'معتدل',
  'Moderate winters, warm summers': 'شتاء معتدل وصيف دافئ',
  'Modified continental': 'قاري معدل',
  'Monsoon': 'موسمي',
  'Mostly arid desert': 'صحراوي جاف في الغالب',
  'Mostly desert': 'صحراوي في الغالب',
  'Mostly hot, dry desert': 'صحراوي حار وجاف في الغالب',
  'Mostly midlatitude desert': 'صحراوي متوسط العرض في الغالب',
  'Mostly temperate': 'معتدل في الغالب',
  'Mostly tropical': 'استوائي في الغالب',
  'Oceanic': 'محيطي',
  'Polar': 'قطبي',
  'Predominantly Mediterranean': 'متوسطي في الغالب',
  'Principally desert': 'صحراوي بشكل أساسي',
  'Ranges from steppes': 'يتراوح من السهوب',
  'Semi-arid': 'شبه جاف',
  'Semi-arid desert': 'صحراوي شبه جاف',
  'Semiarid': 'شبه جاف',
  'Semiarid in south and along coast': 'شبه جاف في الجنوب وعلى الساحل',
  'Steppe': 'سهبي',
  'Subarctic': 'شبه قطبي',
  'Subtropical': 'شبه استوائي',
  'Subtropical climate': 'مناخ شبه استوائي',
  'Subtropical desert': 'صحراوي شبه استوائي',
  'Subtropical highland': 'مرتفع شبه استوائي',
  'Subtropical in lowlands': 'شبه استوائي في الأراضي المنخفضة',
  'Subtropical to arid': 'شبه استوائي إلى جاف',
  'Subtropical to temperate': 'شبه استوائي إلى معتدل',
  'Temperate': 'معتدل',
  'Temperate along coast': 'معتدل على طول الساحل',
  'Temperate and marine': 'معتدل وبحري',
  'Temperate continental': 'قاري معتدل',
  'Temperate in north': 'معتدل في الشمال',
  'Temperate in south': 'معتدل في الجنوب',
  'Temperate maritime': 'بحري معتدل',
  'Transitional, between maritime and continental': 'انتقالي بين بحري وقاري',
  'Tropical': 'استوائي',
  'Tropical along coast': 'استوائي على طول الساحل',
  'Tropical and subtropical': 'استوائي وشبه استوائي',
  'Tropical climate': 'مناخ استوائي',
  'Tropical in lowlands': 'استوائي في الأراضي المنخفضة',
  'Tropical in south': 'استوائي في الجنوب',
  'Tropical in south, arid in north': 'استوائي في الجنوب جاف في الشمال',
  'Tropical marine': 'بحري استوائي',
  'Tropical maritime': 'بحري استوائي',
  'Tropical monsoon': 'رياح موسمية استوائية',
  'Tropical rain forest': 'غابة استوائية مطيرة',
  'Tropical savanna': 'سافانا استوائية',
  'Tropical savanna climate': 'مناخ سافانا استوائية',
  'Tundra': 'تندرا',
  'Varied': 'متنوع',
  'Varies': 'متنوع',
  'Varies from cool summers': 'يختلف من صيف بارد',
  'Varies from temperate in south to subarctic and arctic in north': 'يختلف من معتدل جنوباً إلى شبه قطبي وقطبي شمالاً',
  'Varies from tropical monsoon': 'يختلف من رياح موسمية استوائية',
  'Varies from tropical in east': 'يختلف من استوائي في الشرق',
  'Varies from tropical to desert': 'يختلف من استوائي إلى صحراوي',
  'Varies with altitude': 'يختلف حسب الارتفاع',
  'Varies; tropical in southern plains': 'يختلف؛ استوائي في السهول الجنوبية',
  'Very cold': 'بارد جداً',
  'Warm': 'دافئ',
  'Warm and pleasant': 'دافئ ولطيف',
  'Warm temperate': 'معتدل دافئ',
  'Warm, dry summers and autumns': 'صيف وخريف دافئ وجاف',
};

const governmentMap = {
  'Presidential republic': 'جمهورية رئاسية',
  'Semi-presidential republic': 'جمهورية شبه رئاسية',
  'Parliamentary republic': 'جمهورية برلمانية',
  'Parliamentary constitutional monarchy': 'ملكية دستورية برلمانية',
  'Constitutional monarchy': 'ملكية دستورية',
  'Absolute monarchy': 'ملكية مطلقة',
  'Federal republic': 'جمهورية فيدرالية',
  'Federal parliamentary republic': 'جمهورية برلمانية فيدرالية',
  'Federal presidential republic': 'جمهورية رئاسية فيدرالية',
  'Federal constitutional monarchy': 'ملكية دستورية فيدرالية',
  'Unitary parliamentary republic': 'جمهورية برلمانية موحدة',
  'Unitary presidential republic': 'جمهورية رئاسية موحدة',
  'Unitary semi-presidential republic': 'جمهورية شبه رئاسية موحدة',
  'Communist state': 'دولة شيوعية',
  'Socialist state': 'دولة اشتراكية',
  'Islamic republic': 'جمهورية إسلامية',
  'Theocratic republic': 'جمهورية ثيوقراطية',
  'Parliamentary democracy': 'ديمقراطية برلمانية',
  'Federal parliamentary democracy': 'ديمقراطية برلمانية فيدرالية',
  'Parliamentary system': 'نظام برلماني',
  'Presidential system': 'نظام رئاسي',
  'Semi-presidential system': 'نظام شبه رئاسي',
  'Military junta': 'مجلس عسكري',
  'Provisional government': 'حكومة مؤقتة',
  'Transitional government': 'حكومة انتقالية',
  'Devolved parliamentary legislature': 'هيئة تشريعية برلمانية مفوضة',
  'Federal monarchy': 'ملكية فيدرالية',
  'Constitutional republic': 'جمهورية دستورية',
};

const religionMap = {
  'Islam': 'الإسلام',
  'Christianity': 'المسيحية',
  'Catholicism': 'الكاثوليكية',
  'Protestantism': 'البروتستانتية',
  'Orthodox': 'الأرثوذكسية',
  'Buddhism': 'البوذية',
  'Hinduism': 'الهندوسية',
  'Judaism': 'اليهودية',
  'Sikhism': 'السيخية',
  'Shinto': 'الشنتو',
  'Taoism': 'الطاوية',
  'Confucianism': 'الكونفوشيوسية',
  'Animism': 'الروحانية',
  'Folk religion': 'الدين الشعبي',
  'Traditional faiths': 'المعتقدات التقليدية',
  'Indigenous beliefs': 'المعتقدات الأصلية',
  'African Traditional': 'التقليدي الأفريقي',
  'Sunni Islam': 'الإسلام السني',
  'Shia Islam': 'الإسلام الشيعي',
  'Unaffiliated': 'غير منتسب',
  'None': 'لا شيء',
  'Atheism': 'الإلحاد',
  'Agnosticism': 'اللأدرية',
  'Other': 'أخرى',
  'Irreligion': 'اللادينية',
  'No religion': 'بدون دين',
};

const traditionCategoryMap = {
  'festival': 'مهرجان',
  'custom': 'عادة',
  'ceremony': 'مراسم',
  'art': 'فن',
  'music': 'موسيقى',
  'dance': 'رقص',
  'food': 'طعام',
  'sport': 'رياضة',
  'cultural': 'ثقافي',
  'other': 'أخرى',
};

const attractionCategoryMap = {
  'historical': 'تاريخي',
  'natural': 'طبيعي',
  'cultural': 'ثقافي',
  'religious': 'ديني',
  'adventure': 'مغامرة',
  'beach': 'شاطئ',
  'mountain': 'جبل',
  'city': 'مدينة',
  'other': 'أخرى',
};

const languageMap = {
  'Arabic': 'العربية',
  'Berber': 'الأمازيغية',
  'French': 'الفرنسية',
  'English': 'الإنجليزية',
  'Spanish': 'الإسبانية',
  'Portuguese': 'البرتغالية',
  'German': 'الألمانية',
  'Italian': 'الإيطالية',
  'Dutch': 'الهولندية',
  'Russian': 'الروسية',
  'Chinese': 'الصينية',
  'Mandarin': 'المندرينية',
  'Japanese': 'اليابانية',
  'Korean': 'الكورية',
  'Hindi': 'الهندية',
  'Bengali': 'البنغالية',
  'Urdu': 'الأردية',
  'Punjabi': 'البنجابية',
  'Marathi': 'الماراثية',
  'Gujarati': 'الغوجاراتية',
  'Tamil': 'التاميلية',
  'Telugu': 'التيلوغوية',
  'Kannada': 'الكانادا',
  'Malayalam': 'الماليالامية',
  'Thai': 'التايلاندية',
  'Vietnamese': 'الفيتنامية',
  'Indonesian': 'الإندونيسية',
  'Malay': 'الماليزية',
  'Filipino': 'الفلبينية',
  'Tagalog': 'التاغالوغية',
  'Burmese': 'البورمية',
  'Khmer': 'الخميرية',
  'Lao': 'اللاوية',
  'Sinhala': 'السنهالية',
  'Nepali': 'النيبالية',
  'Dzongkha': 'الزونغخية',
  'Tibetan': 'التبتية',
  'Mongolian': 'المنغولية',
  'Kazakh': 'الكازاخستانية',
  'Uzbek': 'الأوزبكية',
  'Turkmen': 'التركمانية',
  'Kyrgyz': 'القيرغيزية',
  'Tajik': 'الطاجيكية',
  'Pashto': 'البشتوية',
  'Dari': 'الدرية',
  'Azerbaijani': 'الأذرية',
  'Georgian': 'الجورجية',
  'Armenian': 'الأرمينية',
  'Turkish': 'التركية',
  'Greek': 'اليونانية',
  'Albanian': 'الألبانية',
  'Serbian': 'الصربية',
  'Croatian': 'الكرواتية',
  'Bosnian': 'البوسنية',
  'Slovenian': 'السلوفينية',
  'Macedonian': 'المقدونية',
  'Bulgarian': 'البلغارية',
  'Romanian': 'الرومانية',
  'Moldovan': 'المولدوفية',
  'Hungarian': 'المجرية',
  'Polish': 'البولندية',
  'Czech': 'التشيكية',
  'Slovak': 'السلوفاكية',
  'Ukrainian': 'الأوكرانية',
  'Belarusian': 'البيلاروسية',
  'Lithuanian': 'الليتوانية',
  'Latvian': 'اللاتفية',
  'Estonian': 'الإستونية',
  'Finnish': 'الفنلندية',
  'Swedish': 'السويدية',
  'Norwegian': 'النرويجية',
  'Danish': 'الدنماركية',
  'Icelandic': 'الآيسلندية',
  'Dutch ': 'الهولندية',
  'Flemish': 'الفلمنكية',
  'Luxembourgish': 'اللكسمبورغية',
  'Swiss German': 'الألمانية السويسرية',
  'Romansh': 'الرومانشية',
  'Catalan': 'الكتالونية',
  'Basque': 'الباسكية',
  'Galician': 'الجاليكية',
  'Welsh': 'الويلزية',
  'Irish': 'الأيرلندية',
  'Scottish Gaelic': 'الغيلية الإسكتلندية',
  'Maltese': 'المالطية',
  'Icelandic': 'الآيسلندية',
  'Hebrew': 'العبرية',
  'Amharic': 'الأمهرية',
  'Somali': 'الصومالية',
  'Swahili': 'السواحيلية',
  'Hausa': 'الهوسا',
  'Yoruba': 'اليوروبا',
  'Igbo': 'الإيغبو',
  'Zulu': 'الزولو',
  'Xhosa': 'الخوسا',
  'Afrikaans': 'الأفريكانية',
  'Oromo': 'الأورومو',
  'Tigrinya': 'التغرينية',
  'Malagasy': 'الملغاشية',
  'Kinyarwanda': 'الكينيارواندا',
  'Kirundi': 'الكيروندية',
  'Chewa': 'الشيوا',
  'Shona': 'الشونا',
  'Ndebele': 'النديبيلية',
  'Sesotho': 'السيسوتو',
  'Tswana': 'التسوانية',
  'Swati': 'السوازية',
  'Venda': 'الفيندا',
  'Tsonga': 'التسونغا',
  'Sango': 'السانغو',
  'Lingala': 'اللينغالا',
  'Kikongo': 'الكيكونغو',
  'Tshiluba': 'التشيلوبا',
  'Tetum': 'التيتومية',
  'Samoan': 'الساموية',
  'Tongan': 'التونغية',
  'Fijian': 'الفيجية',
  'Kiribati': 'الكيريباتية',
  'Marshallese': 'المارشالية',
  'Palauan': 'البالاوية',
  'Nauruan': 'الناوروية',
  'Tuvaluan': 'التوفالوية',
  'Chamorro': 'التشاموروية',
  'Hiri Motu': 'الهيري موتو',
  'Tok Pisin': 'التوك بيسين',
  'Maori': 'الماورية',
  'Dhivehi': 'المالديفية',
  'Persian': 'الفارسية',
  'Kurdish': 'الكردية',
  'Romansh': 'الرومانشية',
  'Montenegrin': 'الجبل الأسودية',
};

const currencyMap = {
  'United States Dollar (USD)': 'دولار أمريكي (USD)',
  'Euro (EUR)': 'يورو (EUR)',
  'British Pound (GBP)': 'جنيه إسترليني (GBP)',
  'Japanese Yen (JPY)': 'ين ياباني (JPY)',
  'Swiss Franc (CHF)': 'فرنك سويسري (CHF)',
  'Canadian Dollar (CAD)': 'دولار كندي (CAD)',
  'Australian Dollar (AUD)': 'دولار أسترالي (AUD)',
  'Chinese Yuan (CNY)': 'يوان صيني (CNY)',
  'Indian Rupee (INR)': 'روبية هندية (INR)',
  'Russian Ruble (RUB)': 'روبل روسي (RUB)',
  'Brazilian Real (BRL)': 'ريال برازيلي (BRL)',
  'South African Rand (ZAR)': 'راند جنوب أفريقي (ZAR)',
  'Mexican Peso (MXN)': 'بيزو مكسيكي (MXN)',
  'Turkish Lira (TRY)': 'ليرة تركية (TRY)',
  'Saudi Riyal (SAR)': 'ريال سعودي (SAR)',
  'UAE Dirham (AED)': 'درهم إماراتي (AED)',
  'Qatari Riyal (QAR)': 'ريال قطري (QAR)',
  'Kuwaiti Dinar (KWD)': 'دينار كويتي (KWD)',
  'Bahraini Dinar (BHD)': 'دينار بحريني (BHD)',
  'Omani Rial (OMR)': 'ريال عماني (OMR)',
  'Egyptian Pound (EGP)': 'جنيه مصري (EGP)',
  'Algerian Dinar (DZD)': 'دينار جزائري (DZD)',
  'Moroccan Dirham (MAD)': 'درهم مغربي (MAD)',
  'Tunisian Dinar (TND)': 'دينار تونسي (TND)',
  'Libyan Dinar (LYD)': 'دينار ليبي (LYD)',
  'Sudanese Pound (SDG)': 'جنيه سوداني (SDG)',
  'Iraqi Dinar (IQD)': 'دينار عراقي (IQD)',
  'Jordanian Dinar (JOD)': 'دينار أردني (JOD)',
  'Lebanese Pound (LBP)': 'ليرة لبنانية (LBP)',
  'Syrian Pound (SYP)': 'ليرة سورية (SYP)',
  'Yemeni Rial (YER)': 'ريال يمني (YER)',
  'Iranian Rial (IRR)': 'ريال إيراني (IRR)',
  'Pakistani Rupee (PKR)': 'روبية باكستانية (PKR)',
  'Bangladeshi Taka (BDT)': 'تاكا بنغلاديشي (BDT)',
  'Nigerian Naira (NGN)': 'نايراً نيجيرياً (NGN)',
  'Kenyan Shilling (KES)': 'شيلينغ كيني (KES)',
  'Ethiopian Birr (ETB)': 'بير إثيوبي (ETB)',
  'Tanzanian Shilling (TZS)': 'شيلينغ تنزاني (TZS)',
  'Ugandan Shilling (UGX)': 'شيلينغ أوغندي (UGX)',
  'Ghanaian Cedi (GHS)': 'سيدي غاني (GHS)',
  'South Korean Won (KRW)': 'وون كوريا الجنوبية (KRW)',
  'Indonesian Rupiah (IDR)': 'روبية إندونيسية (IDR)',
  'Philippine Peso (PHP)': 'بيزو فلبيني (PHP)',
  'Malaysian Ringgit (MYR)': 'رينغيت ماليزي (MYR)',
  'Singapore Dollar (SGD)': 'دولار سنغافوري (SGD)',
  'Thai Baht (THB)': 'بات تايلاندي (THB)',
  'Vietnamese Dong (VND)': 'دونغ فيتنامي (VND)',
  'Myanmar Kyat (MMK)': 'كيات ميانماري (MMK)',
  'Afghan Afghani (AFN)': 'أفغاني أفغاني (AFN)',
  'Nepalese Rupee (NPR)': 'روبية نيبالية (NPR)',
  'Sri Lankan Rupee (LKR)': 'روبية سريلانكية (LKR)',
  'Maldives Rufiyaa (MVR)': 'روفيه مالديفية (MVR)',
  'Kazakhstani Tenge (KZT)': 'تنغي كازاخستاني (KZT)',
  'Uzbekistani Som (UZS)': 'سوم أوزبكستاني (UZS)',
  'Turkmenistani Manat (TMT)': 'مانات تركمانستاني (TMT)',
  'Kyrgyzstani Som (KGS)': 'سوم قيرغيزستاني (KGS)',
  'Tajikistani Somoni (TJS)': 'سوموني طاجيكستاني (TJS)',
  'Armenian Dram (AMD)': 'درام أرميني (AMD)',
  'Azerbaijani Manat (AZN)': 'مانات أذربيجاني (AZN)',
  'Georgian Lari (GEL)': 'لاري جورجي (GEL)',
  'Polish Zloty (PLN)': 'زلوتي بولندي (PLN)',
  'Czech Koruna (CZK)': 'كرونة تشيكية (CZK)',
  'Hungarian Forint (HUF)': 'فورنت مجري (HUF)',
  'Romanian Leu (RON)': 'ليو روماني (RON)',
  'Bulgarian Lev (BGN)': 'ليف بلغاري (BGN)',
  'Serbian Dinar (RSD)': 'دينار صربي (RSD)',
  'Croatian Kuna (HRK)': 'كونا كرواتية (HRK)',
  'Swedish Krona (SEK)': 'كرونة سويدية (SEK)',
  'Norwegian Krone (NOK)': 'كرونة نرويجية (NOK)',
  'Danish Krone (DKK)': 'كرونة دنماركية (DKK)',
  'Icelandic Krona (ISK)': 'كرونة آيسلندية (ISK)',
  'Albanian Lek (ALL)': 'ليك ألباني (ALL)',
  'Bosnian Convertible Mark (BAM)': 'مارك بوسني قابل للتحويل (BAM)',
  'Macedonian Denar (MKD)': 'دينار مقدوني (MKD)',
  'Moldovan Leu (MDL)': 'ليو مولدوفي (MDL)',
  'Belarusian Ruble (BYN)': 'روبل بيلاروسي (BYN)',
  'Ukrainian Hryvnia (UAH)': 'هريفنيا أوكرانية (UAH)',
  'Argentine Peso (ARS)': 'بيزو أرجنتيني (ARS)',
  'Bolivian Boliviano (BOB)': 'بوليفيانو بوليفي (BOB)',
  'Chilean Peso (CLP)': 'بيزو تشيلي (CLP)',
  'Colombian Peso (COP)': 'بيزو كولومبي (COP)',
  'Ecuadorian Sucre (ECS)': 'سوكري إكوادوري (ECS)',
  'Paraguayan Guarani (PYG)': 'غواراني باراغواي (PYG)',
  'Peruvian Sol (PEN)': 'سول بيروفي (PEN)',
  'Uruguayan Peso (UYU)': 'بيزو أوروغواي (UYU)',
  'Venezuelan Bolivar (VEF)': 'بوليفار فنزويلي (VEF)',
  'Costa Rican Colon (CRC)': 'كولون كوستاريكي (CRC)',
  'Cuban Peso (CUP)': 'بيزو كوبي (CUP)',
  'Dominican Peso (DOP)': 'بيزو دومينيكاني (DOP)',
  'Guatemalan Quetzal (GTQ)': 'كتزال غواتيمالي (GTQ)',
  'Honduran Lempira (HNL)': 'ليمبيرا هندوراسي (HNL)',
  'Nicaraguan Cordoba (NIO)': 'كوردوبا نيكاراغوا (NIO)',
  'Panamanian Balboa (PAB)': 'بالبوا بنمي (PAB)',
  'Salvadoran Colon (SVC)': 'كولون سلفادوري (SVC)',
  'Haitian Gourde (HTG)': 'غورد هايتي (HTG)',
  'Jamaican Dollar (JMD)': 'دولار جامايكي (JMD)',
  'Trinidad and Tobago Dollar (TTD)': 'دولار ترينيداد وتوباغو (TTD)',
  'Barbadian Dollar (BBD)': 'دولار بربادوسي (BBD)',
  'Bahamian Dollar (BSD)': 'دولار باهامي (BSD)',
  'East Caribbean Dollar (XCD)': 'دولار شرق الكاريبي (XCD)',
  'Fiji Dollar (FJD)': 'دولار فيجي (FJD)',
  'Papua New Guinea Kina (PGK)': 'كينا بابوا غينيا الجديدة (PGK)',
  'Solomon Islands Dollar (SBD)': 'دولار جزر سليمان (SBD)',
  'Vanuatu Vatu (VUV)': 'فاتو فانواتو (VUV)',
  'Samoan Tala (WST)': 'تالا ساموا (WST)',
  'Tongan Pa\'anga (TOP)': 'بانغا تونغا (TOP)',
  'Mauritian Rupee (MUR)': 'روبية موريشيوسية (MUR)',
  'Seychelles Rupee (SCR)': 'روبية سيشلية (SCR)',
  'Comorian Franc (KMF)': 'فرنك قمري (KMF)',
  'Djiboutian Franc (DJF)': 'فرنك جيبوتي (DJF)',
  'Eritrean Nakfa (ERN)': 'ناكفا إريترية (ERN)',
  'Angolan Kwanza (AOA)': 'كوانزا أنغولي (AOA)',
  'Botswana Pula (BWP)': 'بولا بوتسواني (BWP)',
  'Burundian Franc (BIF)': 'فرنك بوروندي (BIF)',
  'Cape Verdean Escudo (CVE)': 'إسكودو الرأس الأخضر (CVE)',
  'Central African CFA Franc (XAF)': 'فرنك وسط أفريقي (XAF)',
  'CFP Franc (XPF)': 'فرنك بولينيزيا الفرنسية (XPF)',
  'Congolese Franc (CDF)': 'فرنك كونغولي (CDF)',
  'Equatorial Guinean Ekwele (GQE)': 'إيكويلي غيني استوائي (GQE)',
  'Gambian Dalasi (GMD)': 'دالاسي غامبي (GMD)',
  'Guinean Franc (GNF)': 'فرنك غيني (GNF)',
  'Guinea-Bissau Peso (GWP)': 'بيزو غينيا بيساو (GWP)',
  'Lesotho Loti (LSL)': 'لوتي ليسوتو (LSL)',
  'Liberian Dollar (LRD)': 'دولار ليبيري (LRD)',
  'Malagasy Ariary (MGA)': 'أرياري مدغشقري (MGA)',
  'Malawian Kwacha (MWK)': 'كواتشا ملاوي (MWK)',
  'Mauritanian Ouguiya (MRU)': 'أوقية موريتانية (MRU)',
  'Mozambican Metical (MZN)': 'ميتيكال موزمبيقي (MZN)',
  'Namibian Dollar (NAD)': 'دولار ناميبي (NAD)',
  'Rwandan Franc (RWF)': 'فرنك رواندي (RWF)',
  'Sao Tome and Principe Dobra (STN)': 'دوبرا ساو تومي وبرينسيب (STN)',
  'Sierra Leonean Leone (SLL)': 'ليون سيراليوني (SLL)',
  'Somali Shilling (SOS)': 'شيلينغ صومالي (SOS)',
  'South Sudanese Pound (SSP)': 'جنوب السودان جنيه (SSP)',
  'Swazi Lilangeni (SZL)': 'ليلانغيني سوازيلاندي (SZL)',
  'Zambian Kwacha (ZMW)': 'كواتشا زامبي (ZMW)',
  'Zimbabwean Dollar (ZWD)': 'دولار زيمبابوي (ZWD)',
  'Mongolian Tugrik (MNT)': 'توغروغ منغولي (MNT)',
  'Macanese Pataca (MOP)': 'باتاكا ماكاوي (MOP)',
  'Hong Kong Dollar (HKD)': 'دولار هونغ كونغ (HKD)',
  'New Taiwan Dollar (TWD)': 'دولار تايواني جديد (TWD)',
  'Israeli Shekel (ILS)': 'شيكل إسرائيلي (ILS)',
  'Cambodian Riel (KHR)': 'ريال كمبودي (KHR)',
  'Brunei Dollar (BND)': 'دولار بروناي (BND)',
  'Bhutanese Ngultrum (BTN)': 'نغولترم بوتاني (BTN)',
  'Laotian Kip (LAK)': 'كيب لاوسي (LAK)',
  'Maldivian Rufiyaa (MVR)': 'روفيه مالديفية (MVR)',
  'Timorese Centavo (CVE)': 'سنتافو تيموري (CVE)',
  'New Zealand Dollar (NZD)': 'دولار نيوزيلندي (NZD)',
  'Cuban Peso (CUP)': 'بيزو كوبي (CUP)',
  'Cuban Convertible Peso (CUC)': 'بيزو كوبي قابل للتحويل (CUC)',
};

const capitalMap = {
  'Algiers': 'الجزائر',
  'Luanda': 'لواندا',
  'Porto-Novo': 'بورتو نوفو',
  'Gaborone': 'غابورون',
  'Ouagadougou': 'واغادوغو',
  'Gitega': 'غيتيغا',
  'Praia': 'برايا',
  'Yaoundé': 'ياوندي',
  'Bangui': 'بانغي',
  "N'Djamena": 'انجمينا',
  'Moroni': 'موروني',
  'Brazzaville': 'برازافيل',
  'Yamoussoukro': 'ياموسوكرو',
  'Kinshasa': 'كينشاسا',
  'Djibouti': 'جيبوتي',
  'Cairo': 'القاهرة',
  'Malabo': 'مالابو',
  'Asmara': 'أسمرة',
  'Addis Ababa': 'أديس أبابا',
  'Libreville': 'ليبرفيل',
  'Banjul': 'بانجول',
  'Accra': 'أكرا',
  'Conakry': 'كوناكري',
  'Bissau': 'بيساو',
  'Nairobi': 'نيروبي',
  'Maseru': 'ماسيرو',
  'Monrovia': 'مونروفيا',
  'Tripoli': 'طرابلس',
  'Antananarivo': 'أنتاناناريفو',
  'Lilongwe': 'ليلونغوي',
  'Bamako': 'باماكو',
  'Nouakchott': 'نواكشوط',
  'Port Louis': 'بورت لويس',
  'Rabat': 'الرباط',
  'Maputo': 'مابوتو',
  'Windhoek': 'ويندهوك',
  'Niamey': 'نيامي',
  'Abuja': 'أبوجا',
  'Kigali': 'كيغالي',
  'São Tomé': 'ساو تومي',
  'Dakar': 'داكار',
  'Victoria': 'فيكتوريا',
  'Freetown': 'فريتاون',
  'Mogadishu': 'مقديشو',
  'Pretoria': 'بريتوريا',
  'Juba': 'جوبا',
  'Khartoum': 'الخرطوم',
  'Mbabane': 'مبابان',
  'Dodoma': 'دودوما',
  'Lomé': 'لومي',
  'Tunis': 'تونس',
  'Kampala': 'كامبالا',
  'Lusaka': 'لوساكا',
  'Harare': 'هراري',
  'Kabul': 'كابول',
  'Yerevan': 'يريفان',
  'Baku': 'باكو',
  'Manama': 'المنامة',
  'Dhaka': 'داكا',
  'Thimphu': 'تيمفو',
  'Bandar Seri Begawan': 'بندر سري بكاوان',
  'Phnom Penh': 'بنوم بنه',
  'Beijing': 'بكين',
  'Nicosia': 'نيقوسيا',
  'Dili': 'ديلي',
  'Tbilisi': 'تبليسي',
  'New Delhi': 'نيودلهي',
  'Jakarta': 'جاكرتا',
  'Tehran': 'طهران',
  'Baghdad': 'بغداد',
  'Jerusalem': 'القدس',
  'Tokyo': 'طوكيو',
  'Amman': 'عمان',
  'Nur-Sultan': 'نور سلطان',
  'Astana': 'أستانا',
  'Kuwait City': 'مدينة الكويت',
  'Bishkek': 'بيشكيك',
  'Vientiane': 'فيينتيان',
  'Beirut': 'بيروت',
  'Kuala Lumpur': 'كوالالمبور',
  'Male': 'ماليه',
  'Ulaanbaatar': 'أولان باتور',
  'Naypyidaw': 'نايبيداو',
  'Kathmandu': 'كاثماندو',
  'Pyongyang': 'بيونغ يانغ',
  'Muscat': 'مسقط',
  'Islamabad': 'إسلام آباد',
  'Ramallah': 'رام الله',
  'Manila': 'مانيلا',
  'Doha': 'الدوحة',
  'Moscow': 'موسكو',
  'Riyadh': 'الرياض',
  'Singapore': 'سنغافورة',
  'Seoul': 'سول',
  'Colombo': 'كولومبو',
  'Damascus': 'دمشق',
  'Taipei': 'تايبيه',
  'Dushanbe': 'دوشنبه',
  'Bangkok': 'بانكوك',
  'Ankara': 'أنقرة',
  'Ashgabat': 'عشق آباد',
  'Abu Dhabi': 'أبو ظبي',
  'Tashkent': 'طشقند',
  'Hanoi': 'هانوي',
  "Sana'a": 'صنعاء',
  'Tirana': 'تيرانا',
  'Andorra la Vella': 'أندورا لا فيلا',
  'Vienna': 'فيينا',
  'Minsk': 'مينسك',
  'Brussels': 'بروكسل',
  'Sarajevo': 'سراييفو',
  'Sofia': 'صوفيا',
  'Zagreb': 'زغرب',
  'Prague': 'براغ',
  'Copenhagen': 'كوبنهاغن',
  'Tallinn': 'تالين',
  'Helsinki': 'هلسنكي',
  'Paris': 'باريس',
  'Berlin': 'برلين',
  'Athens': 'أثينا',
  'Budapest': 'بودابست',
  'Reykjavik': 'ريكيافيك',
  'Dublin': 'دبلن',
  'Rome': 'روما',
  'Pristina': 'بريشتينا',
  'Riga': 'ريغا',
  'Vaduz': 'فادوز',
  'Vilnius': 'فيلنيوس',
  'Luxembourg': 'لوكسمبورغ',
  'Valletta': 'فاليتا',
  'Chisinau': 'كيشيناو',
  'Monaco': 'موناكو',
  'Podgorica': 'بودغوريتسا',
  'Amsterdam': 'أمستردام',
  'Skopje': 'إسكوبية',
  'Oslo': 'أوسلو',
  'Warsaw': 'وارسو',
  'Lisbon': 'لشبونة',
  'Bucharest': 'بوخارست',
  'San Marino': 'سان مارينو',
  'Belgrade': 'بلغراد',
  'Bratislava': 'براتيسلافا',
  'Ljubljana': 'ليوبليانا',
  'Madrid': 'مدريد',
  'Stockholm': 'ستوكهولم',
  'Bern': 'برن',
  'Kyiv': 'كييف',
  'London': 'لندن',
  'Vatican City': 'الفاتيكان',
  "St. John's": 'سانت جونز',
  'Buenos Aires': 'بوينس آيرس',
  'Nassau': 'ناساو',
  'Bridgetown': 'بريدج تاون',
  'Belmopan': 'بلموبان',
  'Sucre': 'سوكري',
  'Brasília': 'برازيليا',
  'Ottawa': 'أوتاوا',
  'Santiago': 'سانتياغو',
  'Bogotá': 'بوغوتا',
  'San José': 'سان خوسيه',
  'Havana': 'هافانا',
  'Roseau': 'روسو',
  'Santo Domingo': 'سانتو دومينغو',
  'Quito': 'كيتو',
  'San Salvador': 'سان سلفادور',
  'Palikir': 'باليكير',
  'Suva': 'سوفا',
  "St. George's": 'سانت جورجز',
  'Guatemala City': 'غواتيمالا',
  'Georgetown': 'جورج تاون',
  'Port-au-Prince': 'بورت أو برنس',
  'Tegucigalpa': 'تيغوسيغالبا',
  'Kingston': 'كينغستون',
  'Tarawa': 'تاراوا',
  'Majuro': 'ماجورو',
  'Mexico City': 'مكسيكو سيتي',
  'Managua': 'ماناغوا',
  'Ngerulmud': 'نغيرولمود',
  'Panama City': 'بنما سيتي',
  'Port Moresby': 'بورت مورسبي',
  'Asunción': 'أسونسيون',
  'Lima': 'ليما',
  'Basseterre': 'باستير',
  'Castries': 'كاستري',
  'Kingstown': 'كينغستاون',
  'Apia': 'أبيا',
  'Honiara': 'هونيارا',
  'Paramaribo': 'باراماريبو',
  "Nuku'alofa": 'نوكو ألوفا',
  'Port of Spain': 'بورت أوف سبين',
  'Funafuti': 'فونافوتي',
  'Washington, D.C.': 'واشنطن العاصمة',
  'Montevideo': 'مونتيفيديو',
  'Port Vila': 'بورت فيلا',
  'Caracas': 'كاراكاس',
  'Canberra': 'كانبرا',
  'Wellington': 'ويلينغتون',
  'Avarua': 'أفاروا',
  'Alofi': 'ألوفي',
  'Hamilton': 'هاميلتون',
  'Gustavia': 'غوستافيا',
  'Marigot': 'ماريغو',
  'Saint-Pierre': 'سان بيير',
  'Mata-Utu': 'ماتا أوتو',
  'Adamstown': 'آدمزتاون',
  'Stanley': 'ستانلي',
  'King Edward Point': 'نقطة الملك إدوارد',
  'Longyearbyen': 'لونغياربين',
  'Tórshavn': 'تورسهافن',
  'Gibraltar': 'جبل طارق',
  'Nuuk': 'نوك',
  'Cockburn Town': 'كوكبرن تاون',
  'Douglas': 'دوغلاس',
  'Saint Helier': 'سانت هيلير',
  'Plymouth': 'بليموث',
  'Brades': 'براديس',
  'Little Rock': 'ليتل روك',
  'George Town': 'جورج تاون',
  'Hagåtña': 'هاغاتنيا',
  'Saipan': 'سايبان',
  'San Juan': 'سان خوان',
  'Charlotte Amalie': 'شارلوت أمالي',
  'Road Town': 'رود تاون',
  'Oranjestad': 'أورانياستاد',
  'Philipsburg': 'فيليبسبرغ',
  'The Valley': 'ذا فالي',
  'Basse-Terre': 'باس تير',
  'Fort-de-France': 'فور دو فرانس',
  'Cayenne': 'كايين',
  'Papeete': 'بابيتي',
  'Nouméa': 'نوميا',
};

function localizeCountry(country, lang) {
  if (lang !== 'ar') return country;

  const countryJson = loadArabicData();
  const countryName = country.name;

  const localize = (value, map) => {
    if (!value) return value;
    return map[value] || value;
  };

  const localizeArray = (arr, map) => {
    if (!arr || !Array.isArray(arr)) return arr;
    return arr.map(item => map[item] || item);
  };

  const localized = country.toObject ? country.toObject() : { ...country };

  localized.name = countryJson[countryName] || countryName;
  localized.capital = capitalMap[country.capital] || country.capital;
  localized.continent = continentMap[country.continent] || country.continent;
  localized.currency = currencyMap[country.currency] || country.currency;
  localized.languages = localizeArray(country.languages, languageMap);
  localized.climate = climateMap[country.climate] || country.climate;
  localized.government = governmentMap[country.government] || country.government;
  localized.timezone = country.timezone;

  if (country.independence) {
    try {
      const date = new Date(country.independence);
      if (!isNaN(date.getTime())) {
        localized.independence = date.toLocaleDateString('ar-SA', {
          year: 'numeric', month: 'long', day: 'numeric'
        });
      }
    } catch {}
  }

  if (country.nationalDay) {
    try {
      const date = new Date(country.nationalDay);
      if (!isNaN(date.getTime())) {
        localized.nationalDay = date.toLocaleDateString('ar-SA', {
          month: 'long', day: 'numeric'
        });
      }
    } catch {}
  }

  if (country.geographicLocation?.borders && Array.isArray(country.geographicLocation.borders)) {
    localized.geographicLocation = {
      ...(localized.geographicLocation || {}),
      borders: country.geographicLocation.borders.map(b => countryJson[b] || b),
    };
  }

  if (country.religions && Array.isArray(country.religions)) {
    localized.religions = country.religions.map(r => ({
      ...r.toObject ? r.toObject() : r,
      name: religionMap[r.name] || r.name,
    }));
  }

  if (country.traditions && Array.isArray(country.traditions)) {
    localized.traditions = country.traditions.map(t => ({
      ...t.toObject ? t.toObject() : t,
      category: traditionCategoryMap[t.category] || t.category,
    }));
  }

   if (country.touristAttractions && Array.isArray(country.touristAttractions)) {
     localized.touristAttractions = country.touristAttractions.map(a => {
       const attraction = a.toObject ? a.toObject() : a;
       return {
         ...attraction,
         name: attraction.name, // Keep original name for fallback
         description: attraction.description, // Keep original description for fallback
         location: attraction.location, // Keep original location for fallback
         category: attractionCategoryMap[attraction.category] || attraction.category,
       };
     });
   }

  return localized;
}

module.exports = { localizeCountry };
