const fs = require('fs');
const path = require('path');

let arabicData = null;

function loadArabicData() {
  if (arabicData) return arabicData;
  try {
    arabicData = JSON.parse(
      fs.readFileSync(path.join(__dirname, '..', 'data', 'ar', 'countries.json'), 'utf8')
    );
  } catch {
    arabicData = {};
  }
  return arabicData;
}

const continentMap = {
  'Africa': 'أفريقيا',
  'Asia': 'آسيا',
  'Europe': 'أوروبا',
  'North America': 'أمريكا الشمالية',
  'South America': 'أمريكا الجنوبية',
  'Antarctica': 'أنتاركتيكا',
  'Oceania': 'أوقيانوسيا',
  'Australia': 'أوقيانوسيا',
};

const climateMap = {
  'Arid': 'جاف',
  'Arid or semiarid': 'جاف أو شبه جاف',
  'Arid to semiarid': 'جاف إلى شبه جاف',
  'Cold': 'بارد',
  'Cold temperate': 'معتدل بارد',
  'Cold winters, cool summers': 'شتاء بارد وصيف معتدل',
  'Continental': 'قاري',
  'Cool': 'بارد',
  'Cool temperate': 'معتدل بارد',
  'Desert': 'صحراوي',
  'Desert climate': 'مناخ صحراوي',
  'Diverse': 'متنوع',
  'Dry continental to polar': 'قاري جاف إلى قطبي',
  'Dry desert': 'صحراوي جاف',
  'Dry, semiarid steppe': 'سهب جاف شبه جاف',
  'Equatorial': 'استوائي',
  'Extremely diverse': 'متنوع للغاية',
  'Generally arid to semiarid': 'جاف إلى شبه جاف بشكل عام',
  'Generally cool winters and mild summers': 'شتاء بارد وصيف معتدل بشكل عام',
  'Harsh, dry desert': 'صحراوي جاف قاس',
  'Highland': 'مرتفع',
  'Highland continental': 'قاري مرتفع',
  'Hot': 'حار',
  'Hot and dry': 'حار وجاف',
  'Hot desert': 'صحراوي حار',
  'Hot desert climate': 'مناخ صحراوي حار',
  'Hot summers and cold winters': 'صيف حار وشتاء بارد',
  'Hot with seasonal rainfall': 'حار مع أمطار موسمية',
  'Hot, dry desert': 'صحراوي حار جاف',
  'Humid continental': 'قاري رطب',
  'Humid subtropical': 'شبه استوائي رطب',
  'Marine west coast': 'ساحل غربي بحري',
  'Maritime': 'بحري',
  'Maritime temperate': 'معتدل بحري',
  'Maritime, wet, moderate winters': 'بحري رطب شتاء معتدل',
  'Mediterranean': 'متوسطي',
  'Mediterranean along coast': 'متوسطي على الساحل',
  'Mediterranean and continental': 'متوسطي وقاري',
  'Mediterranean climate': 'مناخ متوسطي',
  'Mediterranean climate on the coast': 'مناخ متوسطي على الساحل',
  'Midlatitude continental': 'قاري متوسط العرض',
  'Mild temperate': 'معتدل لطيف',
  'Moderate': 'معتدل',
  'Moderate winters, warm summers': 'شتاء معتدل وصيف دافئ',
  'Modified continental': 'قاري معدل',
  'Monsoon': 'موسمي',
  'Mostly arid desert': 'صحراوي جاف في الغالب',
  'Mostly desert': 'صحراوي في الغالب',
  'Mostly hot, dry desert': 'صحراوي حار وجاف في الغالب',
  'Mostly midlatitude desert': 'صحراوي متوسط العرض في الغالب',
  'Mostly temperate': 'معتدل في الغالب',
  'Mostly tropical': 'استوائي في الغالب',
  'Oceanic': 'محيطي',
  'Polar': 'قطبي',
  'Predominantly Mediterranean': 'متوسطي في الغالب',
  'Principally desert': 'صحراوي بشكل أساسي',
  'Ranges from steppes': 'يتراوح من السهوب',
  'Semi-arid': 'شبه جاف',
  'Semi-arid desert': 'صحراوي شبه جاف',
  'Semiarid': 'شبه جاف',
  'Semiarid in south and along coast': 'شبه جاف في الجنوب وعلى الساحل',
  'Steppe': 'سهبي',
  'Subarctic': 'شبه قطبي',
  'Subtropical': 'شبه استوائي',
  'Subtropical climate': 'مناخ شبه استوائي',
  'Subtropical desert': 'صحراوي شبه استوائي',
  'Subtropical highland': 'مرتفع شبه استوائي',
  'Subtropical in lowlands': 'شبه استوائي في الأراضي المنخفضة',
  'Subtropical to arid': 'شبه استوائي إلى جاف',
  'Subtropical to temperate': 'شبه استوائي إلى معتدل',
  'Temperate': 'معتدل',
  'Temperate along coast': 'معتدل على طول الساحل',
  'Temperate and marine': 'معتدل وبحري',
  'Temperate continental': 'قاري معتدل',
  'Temperate in north': 'معتدل في الشمال',
  'Temperate in south': 'معتدل في الجنوب',
  'Temperate maritime': 'بحري معتدل',
  'Transitional, between maritime and continental': 'انتقالي بين بحري وقاري',
  'Tropical': 'استوائي',
  'Tropical along coast': 'استوائي على طول الساحل',
  'Tropical and subtropical': 'استوائي وشبه استوائي',
  'Tropical climate': 'مناخ استوائي',
  'Tropical in lowlands': 'استوائي في الأراضي المنخفضة',
  'Tropical in south': 'استوائي في الجنوب',
  'Tropical in south, arid in north': 'استوائي في الجنوب جاف في الشمال',
  'Tropical marine': 'بحري استوائي',
  'Tropical maritime': 'بحري استوائي',
  'Tropical monsoon': 'رياح موسمية استوائية',
  'Tropical rain forest': 'غابة استوائية مطيرة',
  'Tropical savanna': 'سافانا استوائية',
  'Tropical savanna climate': 'مناخ سافانا استوائية',
  'Tundra': 'تندرا',
  'Varied': 'متنوع',
  'Varies': 'متنوع',
  'Varies from cool summers': 'يختلف من صيف بارد',
  'Varies from temperate in south to subarctic and arctic in north': 'يختلف من معتدل جنوباً إلى شبه قطبي وقطبي شمالاً',
  'Varies from tropical monsoon': 'يختلف من رياح موسمية استوائية',
  'Varies from tropical in east': 'يختلف من استوائي في الشرق',
  'Varies from tropical to desert': 'يختلف من استوائي إلى صحراوي',
  'Varies with altitude': 'يختلف حسب الارتفاع',
  'Varies; tropical in southern plains': 'يختلف؛ استوائي في السهول الجنوبية',
  'Very cold': 'بارد جداً',
  'Warm': 'دافئ',
  'Warm and pleasant': 'دافئ ولطيف',
  'Warm temperate': 'معتدل دافئ',
  'Warm, dry summers and autumns': 'صيف وخريف دافئ وجاف',
};

const governmentMap = {
  'Presidential republic': 'جمهورية رئاسية',
  'Semi-presidential republic': 'جمهورية شبه رئاسية',
  'Parliamentary republic': 'جمهورية برلمانية',
  'Parliamentary constitutional monarchy': 'ملكية دستورية برلمانية',
  'Constitutional monarchy': 'ملكية دستورية',
  'Absolute monarchy': 'ملكية مطلقة',
  'Federal republic': 'جمهورية فيدرالية',
  'Federal parliamentary republic': 'جمهورية برلمانية فيدرالية',
  'Federal presidential republic': 'جمهورية رئاسية فيدرالية',
  'Federal constitutional monarchy': 'ملكية دستورية فيدرالية',
  'Unitary parliamentary republic': 'جمهورية برلمانية موحدة',
  'Unitary presidential republic': 'جمهورية رئاسية موحدة',
  'Unitary semi-presidential republic': 'جمهورية شبه رئاسية موحدة',
  'Communist state': 'دولة شيوعية',
  'Socialist state': 'دولة اشتراكية',
  'Islamic republic': 'جمهورية إسلامية',
  'Theocratic republic': 'جمهورية ثيوقراطية',
  'Parliamentary democracy': 'ديمقراطية برلمانية',
  'Federal parliamentary democracy': 'ديمقراطية برلمانية فيدرالية',
  'Parliamentary system': 'نظام برلماني',
  'Presidential system': 'نظام رئاسي',
  'Semi-presidential system': 'نظام شبه رئاسي',
  'Military junta': 'مجلس عسكري',
  'Provisional government': 'حكومة مؤقتة',
  'Transitional government': 'حكومة انتقالية',
  'Devolved parliamentary legislature': 'هيئة تشريعية برلمانية مفوضة',
  'Federal monarchy': 'ملكية فيدرالية',
  'Constitutional republic': 'جمهورية دستورية',
};

const religionMap = {
  'Islam': 'الإسلام',
  'Christianity': 'المسيحية',
  'Catholicism': 'الكاثوليكية',
  'Protestantism': 'البروتستانتية',
  'Orthodox': 'الأرثوذكسية',
  'Buddhism': 'البوذية',
  'Hinduism': 'الهندوسية',
  'Judaism': 'اليهودية',
  'Sikhism': 'السيخية',
  'Shinto': 'الشنتو',
  'Taoism': 'الطاوية',
  'Confucianism': 'الكونفوشيوسية',
  'Animism': 'الروحانية',
  'Folk religion': 'الدين الشعبي',
  'Traditional faiths': 'المعتقدات التقليدية',
  'Indigenous beliefs': 'المعتقدات الأصلية',
  'African Traditional': 'التقليدي الأفريقي',
  'Sunni Islam': 'الإسلام السني',
  'Shia Islam': 'الإسلام الشيعي',
  'Unaffiliated': 'غير منتسب',
  'None': 'لا شيء',
  'Atheism': 'الإلحاد',
  'Agnosticism': 'اللأدرية',
  'Other': 'أخرى',
  'Irreligion': 'اللادينية',
  'No religion': 'بدون دين',
  'Vodun': 'الفودون',
  'Vodou': 'الفودو',
  'Druze': 'الموحدون الدروز',
  'Korean shamanism': 'الشامانية الكورية',
  'Chondoism': 'التشوندوية',
};

const traditionCategoryMap = {
  'festival': 'مهرجان',
  'custom': 'عادة',
  'ceremony': 'مراسم',
  'art': 'فن',
  'music': 'موسيقى',
  'dance': 'رقص',
  'food': 'طعام',
  'sport': 'رياضة',
  'cultural': 'ثقافي',
  'other': 'أخرى',
};

const attractionCategoryMap = {
  'historical': 'تاريخي',
  'natural': 'طبيعي',
  'cultural': 'ثقافي',
  'religious': 'ديني',
  'adventure': 'مغامرة',
  'beach': 'شاطئ',
  'mountain': 'جبل',
  'city': 'مدينة',
  'other': 'أخرى',
};

const languageMap = {
  'Arabic': 'العربية',
  'Berber': 'الأمازيغية',
  'French': 'الفرنسية',
  'English': 'الإنجليزية',
  'Spanish': 'الإسبانية',
  'Portuguese': 'البرتغالية',
  'German': 'الألمانية',
  'Italian': 'الإيطالية',
  'Dutch': 'الهولندية',
  'Russian': 'الروسية',
  'Chinese': 'الصينية',
  'Mandarin': 'المندرينية',
  'Japanese': 'اليابانية',
  'Korean': 'الكورية',
  'Hindi': 'الهندية',
  'Bengali': 'البنغالية',
  'Urdu': 'الأردية',
  'Punjabi': 'البنجابية',
  'Marathi': 'الماراثية',
  'Gujarati': 'الغوجاراتية',
  'Tamil': 'التاميلية',
  'Telugu': 'التيلوغوية',
  'Kannada': 'الكانادا',
  'Malayalam': 'الماليالامية',
  'Thai': 'التايلاندية',
  'Vietnamese': 'الفيتنامية',
  'Indonesian': 'الإندونيسية',
  'Malay': 'الماليزية',
  'Filipino': 'الفلبينية',
  'Tagalog': 'التاغالوغية',
  'Burmese': 'البورمية',
  'Khmer': 'الخميرية',
  'Lao': 'اللاوية',
  'Sinhala': 'السنهالية',
  'Nepali': 'النيبالية',
  'Dzongkha': 'الزونغخية',
  'Tibetan': 'التبتية',
  'Mongolian': 'المنغولية',
  'Kazakh': 'الكازاخستانية',
  'Uzbek': 'الأوزبكية',
  'Turkmen': 'التركمانية',
  'Kyrgyz': 'القيرغيزية',
  'Tajik': 'الطاجيكية',
  'Pashto': 'البشتوية',
  'Dari': 'الدرية',
  'Azerbaijani': 'الأذرية',
  'Georgian': 'الجورجية',
  'Armenian': 'الأرمينية',
  'Turkish': 'التركية',
  'Greek': 'اليونانية',
  'Albanian': 'الألبانية',
  'Serbian': 'الصربية',
  'Croatian': 'الكرواتية',
  'Bosnian': 'البوسنية',
  'Slovenian': 'السلوفينية',
  'Macedonian': 'المقدونية',
  'Bulgarian': 'البلغارية',
  'Romanian': 'الرومانية',
  'Moldovan': 'المولدوفية',
  'Hungarian': 'المجرية',
  'Polish': 'البولندية',
  'Czech': 'التشيكية',
  'Slovak': 'السلوفاكية',
  'Ukrainian': 'الأوكرانية',
  'Belarusian': 'البيلاروسية',
  'Lithuanian': 'الليتوانية',
  'Latvian': 'اللاتفية',
  'Estonian': 'الإستونية',
  'Finnish': 'الفنلندية',
  'Swedish': 'السويدية',
  'Norwegian': 'النرويجية',
  'Danish': 'الدنماركية',
  'Icelandic': 'الآيسلندية',
  'Dutch ': 'الهولندية',
  'Flemish': 'الفلمنكية',
  'Luxembourgish': 'اللكسمبورغية',
  'Swiss German': 'الألمانية السويسرية',
  'Romansh': 'الرومانشية',
  'Catalan': 'الكتالونية',
  'Basque': 'الباسكية',
  'Galician': 'الجاليكية',
  'Welsh': 'الويلزية',
  'Irish': 'الأيرلندية',
  'Scottish Gaelic': 'الغيلية الإسكتلندية',
  'Maltese': 'المالطية',
  'Icelandic': 'الآيسلندية',
  'Hebrew': 'العبرية',
  'Amharic': 'الأمهرية',
  'Somali': 'الصومالية',
  'Swahili': 'السواحيلية',
  'Hausa': 'الهوسا',
  'Yoruba': 'اليوروبا',
  'Igbo': 'الإيغبو',
  'Zulu': 'الزولو',
  'Xhosa': 'الخوسا',
  'Afrikaans': 'الأفريكانية',
  'Oromo': 'الأورومو',
  'Tigrinya': 'التغرينية',
  'Malagasy': 'الملغاشية',
  'Kinyarwanda': 'الكينيارواندا',
  'Kirundi': 'الكيروندية',
  'Chewa': 'الشيوا',
  'Shona': 'الشونا',
  'Ndebele': 'النديبيلية',
  'Sesotho': 'السيسوتو',
  'Tswana': 'التسوانية',
  'Swati': 'السوازية',
  'Venda': 'الفيندا',
  'Tsonga': 'التسونغا',
  'Sango': 'السانغو',
  'Lingala': 'اللينغالا',
  'Kikongo': 'الكيكونغو',
  'Tshiluba': 'التشيلوبا',
  'Tetum': 'التيتومية',
  'Samoan': 'الساموية',
  'Tongan': 'التونغية',
  'Fijian': 'الفيجية',
  'Kiribati': 'الكيريباتية',
  'Marshallese': 'المارشالية',
  'Palauan': 'البالاوية',
  'Nauruan': 'الناوروية',
  'Tuvaluan': 'التوفالوية',
  'Chamorro': 'التشاموروية',
  'Hiri Motu': 'الهيري موتو',
  'Tok Pisin': 'التوك بيسين',
  'Maori': 'الماورية',
  'Dhivehi': 'المالديفية',
  'Persian': 'الفارسية',
  'Kurdish': 'الكردية',
  'Romansh': 'الرومانشية',
  'Montenegrin': 'الجبل الأسودية',
  'Aramaic': 'الآرامية',
  'Aymara': 'الأيمارا',
  'Belizean Creole': 'الكريول البليزية',
  'Bislama': 'البيسلامية',
  'Chibarwe': 'الشيباروي',
  'Comorian': 'القمرية',
  'Fiji Hindi': 'الهندية الفيجية',
  'Gilbertese': 'الكيريباتية',
  'Guaraní': 'الغوارانية',
  'Haitian Creole': 'الكريول الهايتية',
  'Herero': 'الهيريرو',
  'Jamaican Patois': 'باتوا الجامايكية',
  'Kalanga': 'الكالانغا',
  'Khoekhoe': 'الخويخوي',
  'Khoisan': 'الخويسان',
  'Kwangali': 'الكوانغالي',
  'Latin': 'اللاتينية',
  'Lozi': 'اللوزي',
  'Maldivian': 'المالديفية',
  'Mauritian Creole': 'الكريول الموريشيوسية',
  'Māori': 'الماورية',
  'Nauru': 'الناوروية',
  'Ndau': 'النداو',
  'Ndonga': 'الندونغا',
  'New Zealand Sign Language': 'لغة الإشارة النيوزيلندية',
  'Northern Ndebele': 'النديبيل الشمالية',
  'Northern Sotho': 'السوتو الشمالية',
  'Norwegian Bokmål': 'النرويجية بوكمول',
  'Norwegian Nynorsk': 'النرويجية نينوشك',
  'Persian (Farsi)': 'الفارسية',
  'Quechua': 'الكيشوا',
  'Sami': 'السامية',
  'Seychellois Creole': 'الكريول السيشلية',
  'Slovene': 'السلوفينية',
  'Sorani': 'السورانية',
  'Sotho': 'السوتو',
  'Southern Ndebele': 'النديبيل الجنوبية',
  'Southern Sotho': 'السوتو الجنوبية',
  'Swazi': 'السوازية',
  'Tonga': 'التونغية',
  'Upper Guinea Creole': 'كريول غينيا العليا',
  'Zimbabwean Sign Language': 'لغة الإشارة الزيمبابوية',
};

const currencyMap = {
  'Afghan afghani': 'أفغاني أفغاني',
  'Albanian lek': 'ليك ألباني',
  'Algerian dinar': 'دينار جزائري',
  'Angolan kwanza': 'كوانزا أنغولي',
  'Argentine peso': 'بيزو أرجنتيني',
  'Armenian dram': 'درام أرميني',
  'Australian dollar': 'دولار أسترالي',
  'Australian dollar, Kiribati dollar': 'دولار أسترالي، دولار كيريباتي',
  'Australian dollar, Tuvaluan dollar': 'دولار أسترالي، دولار توفالو',
  'Azerbaijani manat': 'مانات أذربيجاني',
  'Bahamian dollar, United States dollar': 'دولار باهامي، دولار أمريكي',
  'Bahraini dinar': 'دينار بحريني',
  'Bangladeshi taka': 'تاكا بنغلاديشي',
  'Barbadian dollar': 'دولار بربادوسي',
  'Belarusian ruble': 'روبل بيلاروسي',
  'Belize dollar': 'دولار بليزي',
  'Bhutanese ngultrum, Indian rupee': 'نغولترم بوتاني، روبية هندية',
  'Bolivian boliviano': 'بوليفيانو بوليفي',
  'Bosnia and Herzegovina convertible mark': 'مارك قابل للتحول البوسني',
  'Botswana pula': 'بولا بوتسواني',
  'Brazilian real': 'ريال برازيلي',
  'British pound': 'جنيه إسترليني',
  'Brunei dollar, Singapore dollar': 'دولار بروناي، دولار سنغافوري',
  'Bulgarian lev': 'ليف بلغاري',
  'Burmese kyat': 'كيات بورمي',
  'Burundian franc': 'فرنك بوروندي',
  'Cambodian riel, United States dollar': 'رييل كمبودي، دولار أمريكي',
  'Canadian dollar': 'دولار كندي',
  'Cape Verdean escudo': 'إسكودو الرأس الأخضر',
  'Central African CFA franc': 'فرنك وسط أفريقي',
  'Chilean peso': 'بيزو تشيلي',
  'Chinese yuan': 'يوان صيني',
  'Colombian peso': 'بيزو كولومبي',
  'Comorian franc': 'فرنك قمري',
  'Congolese franc': 'فرنك كونغولي',
  'Costa Rican colón': 'كولون كوستاريكي',
  'Cuban convertible peso, Cuban peso': 'بيزو كوبي قابل للتحويل، بيزو كوبي',
  'Czech koruna': 'كرونة تشيكية',
  'Danish krone': 'كرونة دنماركية',
  'Djiboutian franc': 'فرنك جيبوتي',
  'Dominican peso': 'بيزو دومينيكاني',
  'Eastern Caribbean dollar': 'دولار شرق الكاريبي',
  'Egyptian pound': 'جنيه مصري',
  'Egyptian pound, Israeli new shekel, Jordanian dinar': 'جنيه مصري، شيكل إسرائيلي، دينار أردني',
  'Eritrean nakfa': 'ناكفا إريترية',
  'Ethiopian birr': 'بير إثيوبي',
  'Fijian dollar': 'دولار فيجي',
  'Ghanaian cedi': 'سيدي غاني',
  'Guatemalan quetzal': 'كتزال غواتيمالي',
  'Guinean franc': 'فرنك غيني',
  'Guyanese dollar': 'دولار غياني',
  'Haitian gourde': 'غورد هايتي',
  'Honduran lempira': 'ليمبيرا هندوراسي',
  'Hungarian forint': 'فورنت مجري',
  'Icelandic króna': 'كرونة آيسلندية',
  'Indian rupee': 'روبية هندية',
  'Indonesian rupiah': 'روبية إندونيسية',
  'Iranian rial': 'ريال إيراني',
  'Iraqi dinar': 'دينار عراقي',
  'Israeli new shekel': 'شيكل إسرائيلي',
  'Jamaican dollar': 'دولار جامايكي',
  'Japanese yen': 'ين ياباني',
  'Jordanian dinar': 'دينار أردني',
  'Kazakhstani tenge': 'تنغي كازاخستاني',
  'Kenyan shilling': 'شيلينغ كيني',
  'Kuwaiti dinar': 'دينار كويتي',
  'Kyrgyzstani som': 'سوم قيرغيزستاني',
  'Lao kip': 'كيب لاوسي',
  'Lebanese pound': 'ليرة لبنانية',
  'Leone': 'ليون سيراليوني',
  'Lesotho loti, South African rand': 'لوتي ليسوتو، راند جنوب أفريقي',
  'Liberian dollar': 'دولار ليبيري',
  'Libyan dinar': 'دينار ليبي',
  'Malagasy ariary': 'أرياري مدغشقري',
  'Malawian kwacha': 'كواتشا ملاوي',
  'Malaysian ringgit': 'رينغيت ماليزي',
  'Maldivian rufiyaa': 'روفيه مالديفية',
  'Mauritanian ouguiya': 'أوقية موريتانية',
  'Mauritian rupee': 'روبية موريشيوسية',
  'Mexican peso': 'بيزو مكسيكي',
  'Moldovan leu': 'ليو مولدوفي',
  'Mongolian tögrög': 'توغروغ منغولي',
  'Moroccan dirham': 'درهم مغربي',
  'Mozambican metical': 'ميتيكال موزمبيقي',
  'Namibian dollar, South African rand': 'دولار ناميبي، راند جنوب أفريقي',
  'Nepalese rupee': 'روبية نيبالية',
  'New Taiwan dollar': 'دولار تايواني جديد',
  'New Zealand dollar': 'دولار نيوزيلندي',
  'Nicaraguan córdoba': 'كوردوبا نيكاراغوا',
  'Nigerian naira': 'نايرا نيجيري',
  'North Korean won': 'وون كوريا الشمالية',
  'Norwegian krone': 'كرونة نرويجية',
  'Omani rial': 'ريال عماني',
  'Pakistani rupee': 'روبية باكستانية',
  'Panamanian balboa, United States dollar': 'بالبوا بنمي، دولار أمريكي',
  'Papua New Guinean kina': 'كينا بابوا غينيا الجديدة',
  'Paraguayan guaraní': 'غواراني باراغواي',
  'Peruvian sol': 'سول بيروفي',
  'Philippine peso': 'بيزو فلبيني',
  'Polish złoty': 'زلوتي بولندي',
  'Qatari riyal': 'ريال قطري',
  'Romanian leu': 'ليو روماني',
  'Russian ruble': 'روبل روسي',
  'Rwandan franc': 'فرنك رواندي',
  'Samoan tālā': 'تالا ساموا',
  'Saudi riyal': 'ريال سعودي',
  'Serbian dinar': 'دينار صربي',
  'Seychellois rupee': 'روبية سيشلية',
  'Singapore dollar': 'دولار سنغافوري',
  'Solomon Islands dollar': 'دولار جزر سليمان',
  'Somali shilling': 'شيلينغ صومالي',
  'South African rand': 'راند جنوب أفريقي',
  'South Korean won': 'وون كوريا الجنوبية',
  'South Sudanese pound': 'جنيه جنوب السودان',
  'Sri Lankan rupee': 'روبية سريلانكية',
  'Sudanese pound': 'جنيه سوداني',
  'Surinamese dollar': 'دولار سورينامي',
  'Swazi lilangeni, South African rand': 'ليلانغيني سوازيلاندي، راند جنوب أفريقي',
  'Swedish krona': 'كرونة سويدية',
  'Swiss franc': 'فرنك سويسري',
  'Syrian pound': 'ليرة سورية',
  'São Tomé and Príncipe dobra': 'دوبرا ساو تومي وبرينسيب',
  'Tajikistani somoni': 'سوموني طاجيكستاني',
  'Tanzanian shilling': 'شيلينغ تنزاني',
  'Thai baht': 'بات تايلاندي',
  'Tongan paʻanga': 'بانغا تونغا',
  'Trinidad and Tobago dollar': 'دولار ترينيداد وتوباغو',
  'Tunisian dinar': 'دينار تونسي',
  'Turkish lira': 'ليرة تركية',
  'Turkmenistan manat': 'مانات تركمانستاني',
  'Ugandan shilling': 'شيلينغ أوغندي',
  'Ukrainian hryvnia': 'هريفنيا أوكرانية',
  'United Arab Emirates dirham': 'درهم إماراتي',
  'United States dollar': 'دولار أمريكي',
  'Uruguayan peso': 'بيزو أوروغواي',
  'Uzbekistani soʻm': 'سوم أوزبكستاني',
  'Vanuatu vatu': 'فاتو فانواتو',
  'Venezuelan bolívar soberano': 'بوليفار فنزويلي سيادي',
  'Vietnamese đồng': 'دونغ فيتنامي',
  'West African CFA franc': 'فرنك غرب أفريقي',
  'Yemeni rial': 'ريال يمني',
  'Zambian kwacha': 'كواتشا زامبي',
  'Zimbabwean dollar': 'دولار زيمبابوي',
  'dalasi': 'دالاسي غامبي',
  'denar': 'دينار مقدوني',
  'euro': 'يورو',
  'lari': 'لاري جورجي',
};

const timezoneMap = {
  'UTC': 'التوقيت العالمي المنسق (UTC)',
  'UTC+00:00': 'التوقيت العالمي المنسق +00:00',
  'UTC+01:00': 'التوقيت العالمي المنسق +01:00',
  'UTC+02:00': 'التوقيت العالمي المنسق +02:00',
  'UTC+03:00': 'التوقيت العالمي المنسق +03:00',
  'UTC+03:30': 'التوقيت العالمي المنسق +03:30',
  'UTC+04:00': 'التوقيت العالمي المنسق +04:00',
  'UTC+04:30': 'التوقيت العالمي المنسق +04:30',
  'UTC+05:00': 'التوقيت العالمي المنسق +05:00',
  'UTC+05:30': 'التوقيت العالمي المنسق +05:30',
  'UTC+05:45': 'التوقيت العالمي المنسق +05:45',
  'UTC+06:00': 'التوقيت العالمي المنسق +06:00',
  'UTC+06:30': 'التوقيت العالمي المنسق +06:30',
  'UTC+07:00': 'التوقيت العالمي المنسق +07:00',
  'UTC+08:00': 'التوقيت العالمي المنسق +08:00',
  'UTC+09:00': 'التوقيت العالمي المنسق +09:00',
  'UTC+09:30': 'التوقيت العالمي المنسق +09:30',
  'UTC+10:00': 'التوقيت العالمي المنسق +10:00',
  'UTC+10:30': 'التوقيت العالمي المنسق +10:30',
  'UTC+11:00': 'التوقيت العالمي المنسق +11:00',
  'UTC+11:30': 'التوقيت العالمي المنسق +11:30',
  'UTC+12:00': 'التوقيت العالمي المنسق +12:00',
  'UTC+12:45': 'التوقيت العالمي المنسق +12:45',
  'UTC+13:00': 'التوقيت العالمي المنسق +13:00',
  'UTC+14:00': 'التوقيت العالمي المنسق +14:00',
  'UTC-01:00': 'التوقيت العالمي المنسق -01:00',
  'UTC-02:00': 'التوقيت العالمي المنسق -02:00',
  'UTC-03:00': 'التوقيت العالمي المنسق -03:00',
  'UTC-03:30': 'التوقيت العالمي المنسق -03:30',
  'UTC-04:00': 'التوقيت العالمي المنسق -04:00',
  'UTC-05:00': 'التوقيت العالمي المنسق -05:00',
  'UTC-06:00': 'التوقيت العالمي المنسق -06:00',
  'UTC-07:00': 'التوقيت العالمي المنسق -07:00',
  'UTC-08:00': 'التوقيت العالمي المنسق -08:00',
  'UTC-09:00': 'التوقيت العالمي المنسق -09:00',
  'UTC-09:30': 'التوقيت العالمي المنسق -09:30',
  'UTC-10:00': 'التوقيت العالمي المنسق -10:00',
  'UTC-11:00': 'التوقيت العالمي المنسق -11:00',
  'UTC-12:00': 'التوقيت العالمي المنسق -12:00',
};

const borderCodeMap = (() => {
  const m = {};
  const entries = [
    ['AFG', 'أفغانستان'],
    ['AGO', 'أنغولا'],
    ['ALB', 'ألبانيا'],
    ['AND', 'أندورا'],
    ['ARE', 'الإمارات العربية المتحدة'],
    ['ARG', 'الأرجنتين'],
    ['ARM', 'أرمينيا'],
    ['AUT', 'النمسا'],
    ['AZE', 'أذربيجان'],
    ['BDI', 'بوروندي'],
    ['BEL', 'بلجيكا'],
    ['BEN', 'بنين'],
    ['BFA', 'بوركينا فاسو'],
    ['BGD', 'بنغلاديش'],
    ['BGR', 'بلغاريا'],
    ['BIH', 'البوسنة والهرسك'],
    ['BLR', 'بيلاروسيا'],
    ['BLZ', 'بليز'],
    ['BOL', 'بوليفيا'],
    ['BRA', 'البرازيل'],
    ['BRN', 'بروناي'],
    ['BTN', 'بوتان'],
    ['BWA', 'بوتسوانا'],
    ['CAF', 'جمهورية أفريقيا الوسطى'],
    ['CAN', 'كندا'],
    ['CHE', 'سويسرا'],
    ['CHL', 'تشيلي'],
    ['CHN', 'الصين'],
    ['CIV', 'ساحل العاج'],
    ['CMR', 'الكاميرون'],
    ['COD', 'جمهورية الكونغو الديمقراطية'],
    ['COG', 'جمهورية الكونغو'],
    ['COL', 'كولومبيا'],
    ['CRI', 'كوستاريكا'],
    ['CZE', 'جمهورية التشيك'],
    ['DEU', 'ألمانيا'],
    ['DJI', 'جيبوتي'],
    ['DNK', 'الدنمارك'],
    ['DOM', 'جمهورية الدومينيكان'],
    ['DZA', 'الجزائر'],
    ['ECU', 'الإكوادور'],
    ['EGY', 'مصر'],
    ['ERI', 'إريتريا'],
    ['ESH', 'الصحراء الغربية'],
    ['ESP', 'إسبانيا'],
    ['EST', 'إستونيا'],
    ['ETH', 'إثيوبيا'],
    ['FIN', 'فنلندا'],
    ['FRA', 'فرنسا'],
    ['GAB', 'الغابون'],
    ['GBR', 'المملكة المتحدة'],
    ['GEO', 'جورجيا'],
    ['GHA', 'غانا'],
    ['GIB', 'جبل طارق'],
    ['GIN', 'غينيا'],
    ['GMB', 'غامبيا'],
    ['GNB', 'غينيا بيساو'],
    ['GNQ', 'غينيا الاستوائية'],
    ['GRC', 'اليونان'],
    ['GTM', 'غواتيمالا'],
    ['GUF', 'غويانا الفرنسية'],
    ['GUY', 'غيانا'],
    ['HKG', 'هونغ كونغ'],
    ['HND', 'هندوراس'],
    ['HRV', 'كرواتيا'],
    ['HTI', 'هايتي'],
    ['HUN', 'المجر'],
    ['IDN', 'إندونيسيا'],
    ['IND', 'الهند'],
    ['IRL', 'أيرلندا'],
    ['IRN', 'إيران'],
    ['IRQ', 'العراق'],
    ['ISR', 'إسرائيل'],
    ['ITA', 'إيطاليا'],
    ['JOR', 'الأردن'],
    ['KAZ', 'كازاخستان'],
    ['KEN', 'كينيا'],
    ['KGZ', 'قيرغيزستان'],
    ['KHM', 'كمبوديا'],
    ['KOR', 'كوريا الجنوبية'],
    ['KWT', 'الكويت'],
    ['LAO', 'لاوس'],
    ['LBN', 'لبنان'],
    ['LBR', 'ليبيريا'],
    ['LBY', 'ليبيا'],
    ['LIE', 'ليختنشتاين'],
    ['LSO', 'ليسوتو'],
    ['LTU', 'ليتوانيا'],
    ['LUX', 'لوكسمبورغ'],
    ['LVA', 'لاتفيا'],
    ['MAC', 'ماكاو'],
    ['MAR', 'المغرب'],
    ['MCO', 'موناكو'],
    ['MDA', 'مولدوفا'],
    ['MEX', 'المكسيك'],
    ['MKD', 'مقدونيا الشمالية'],
    ['MLI', 'مالي'],
    ['MMR', 'ميانمار'],
    ['MNE', 'الجبل الأسود'],
    ['MNG', 'منغوليا'],
    ['MOZ', 'موزمبيق'],
    ['MRT', 'موريتانيا'],
    ['MWI', 'ملاوي'],
    ['MYS', 'ماليزيا'],
    ['NAM', 'ناميبيا'],
    ['NER', 'النيجر'],
    ['NGA', 'نيجيريا'],
    ['NIC', 'نيكاراغوا'],
    ['NLD', 'هولندا'],
    ['NOR', 'النرويج'],
    ['NPL', 'نيبال'],
    ['OMN', 'عُمان'],
    ['PAK', 'باكستان'],
    ['PAN', 'بنما'],
    ['PER', 'بيرو'],
    ['PNG', 'بابوا غينيا الجديدة'],
    ['POL', 'بولندا'],
    ['PRK', 'كوريا الشمالية'],
    ['PRT', 'البرتغال'],
    ['PRY', 'باراغواي'],
    ['PSE', 'فلسطين'],
    ['QAT', 'قطر'],
    ['ROU', 'رومانيا'],
    ['RUS', 'روسيا'],
    ['RWA', 'رواندا'],
    ['SAU', 'المملكة العربية السعودية'],
    ['SDN', 'السودان'],
    ['SEN', 'السنغال'],
    ['SLE', 'سيراليون'],
    ['SLV', 'السلفادور'],
    ['SMR', 'سان مارينو'],
    ['SOM', 'الصومال'],
    ['SRB', 'صربيا'],
    ['SSD', 'جنوب السودان'],
    ['SUR', 'سورينام'],
    ['SVK', 'سلوفاكيا'],
    ['SVN', 'سلوفينيا'],
    ['SWE', 'السويد'],
    ['SWZ', 'إسواتيني'],
    ['SYR', 'سوريا'],
    ['TCD', 'تشاد'],
    ['TGO', 'توغو'],
    ['THA', 'تايلاند'],
    ['TJK', 'طاجيكستان'],
    ['TKM', 'تركمانستان'],
    ['TLS', 'تيمور الشرقية'],
    ['TUN', 'تونس'],
    ['TUR', 'تركيا'],
    ['TZA', 'تنزانيا'],
    ['UGA', 'أوغندا'],
    ['UKR', 'أوكرانيا'],
    ['UNK', 'كوسوفو'],
    ['URY', 'الأوروغواي'],
    ['USA', 'الولايات المتحدة'],
    ['UZB', 'أوزبكستان'],
    ['VAT', 'الفاتيكان'],
    ['VEN', 'فنزويلا'],
    ['VNM', 'فيتنام'],
    ['YEM', 'اليمن'],
    ['ZAF', 'جنوب أفريقيا'],
    ['ZMB', 'زامبيا'],
    ['ZWE', 'زيمبابوي'],
  ];
  entries.forEach(([k, v]) => { m[k] = v; });
  return m;
})();

const capitalMap = {
  'Algiers': 'الجزائر',
  'Luanda': 'لواندا',
  'Porto-Novo': 'بورتو نوفو',
  'Gaborone': 'غابورون',
  'Ouagadougou': 'واغادوغو',
  'Gitega': 'غيتيغا',
  'Praia': 'برايا',
  'Yaoundé': 'ياوندي',
  'Bangui': 'بانغي',
  "N'Djamena": 'انجمينا',
  'Moroni': 'موروني',
  'Brazzaville': 'برازافيل',
  'Yamoussoukro': 'ياموسوكرو',
  'Kinshasa': 'كينشاسا',
  'Djibouti': 'جيبوتي',
  'Cairo': 'القاهرة',
  'Malabo': 'مالابو',
  'Asmara': 'أسمرة',
  'Addis Ababa': 'أديس أبابا',
  'Libreville': 'ليبرفيل',
  'Banjul': 'بانجول',
  'Accra': 'أكرا',
  'Conakry': 'كوناكري',
  'Bissau': 'بيساو',
  'Nairobi': 'نيروبي',
  'Maseru': 'ماسيرو',
  'Monrovia': 'مونروفيا',
  'Tripoli': 'طرابلس',
  'Antananarivo': 'أنتاناناريفو',
  'Lilongwe': 'ليلونغوي',
  'Bamako': 'باماكو',
  'Nouakchott': 'نواكشوط',
  'Port Louis': 'بورت لويس',
  'Rabat': 'الرباط',
  'Maputo': 'مابوتو',
  'Windhoek': 'ويندهوك',
  'Niamey': 'نيامي',
  'Abuja': 'أبوجا',
  'Kigali': 'كيغالي',
  'São Tomé': 'ساو تومي',
  'Dakar': 'داكار',
  'Victoria': 'فيكتوريا',
  'Freetown': 'فريتاون',
  'Mogadishu': 'مقديشو',
  'Pretoria': 'بريتوريا',
  'Juba': 'جوبا',
  'Khartoum': 'الخرطوم',
  'Ciudad de la Paz': 'سيوداد دي لا باز',
  "Saint John's": 'سانت جونز',
  'Ulan Bator': 'أولان باتور',
  'Sri Jayawardenepura Kotte': 'سري جاياواردنابورا كوتي',
  'Malé': 'ماليه',
  'Chișinău': 'كيشيناو',
  'City of San Marino': 'مدينة سان مارينو',
  'South Tarawa': 'تاراوا الجنوبية',
  'Yaren': 'يارين',
  'Mbabane': 'مبابان',
  'Dodoma': 'دودوما',
  'Lomé': 'لومي',
  'Tunis': 'تونس',
  'Kampala': 'كامبالا',
  'Lusaka': 'لوساكا',
  'Harare': 'هراري',
  'Kabul': 'كابول',
  'Yerevan': 'يريفان',
  'Baku': 'باكو',
  'Manama': 'المنامة',
  'Dhaka': 'داكا',
  'Thimphu': 'تيمفو',
  'Bandar Seri Begawan': 'بندر سري بكاوان',
  'Phnom Penh': 'بنوم بنه',
  'Beijing': 'بكين',
  'Nicosia': 'نيقوسيا',
  'Dili': 'ديلي',
  'Tbilisi': 'تبليسي',
  'New Delhi': 'نيودلهي',
  'Jakarta': 'جاكرتا',
  'Tehran': 'طهران',
  'Baghdad': 'بغداد',
  'Jerusalem': 'القدس',
  'Tokyo': 'طوكيو',
  'Amman': 'عمان',
  'Nur-Sultan': 'نور سلطان',
  'Astana': 'أستانا',
  'Kuwait City': 'مدينة الكويت',
  'Bishkek': 'بيشكيك',
  'Vientiane': 'فيينتيان',
  'Beirut': 'بيروت',
  'Kuala Lumpur': 'كوالالمبور',
  'Male': 'ماليه',
  'Ulaanbaatar': 'أولان باتور',
  'Naypyidaw': 'نايبيداو',
  'Kathmandu': 'كاثماندو',
  'Pyongyang': 'بيونغ يانغ',
  'Muscat': 'مسقط',
  'Islamabad': 'إسلام آباد',
  'Ramallah': 'رام الله',
  'Manila': 'مانيلا',
  'Doha': 'الدوحة',
  'Moscow': 'موسكو',
  'Riyadh': 'الرياض',
  'Singapore': 'سنغافورة',
  'Seoul': 'سول',
  'Colombo': 'كولومبو',
  'Damascus': 'دمشق',
  'Taipei': 'تايبيه',
  'Dushanbe': 'دوشنبه',
  'Bangkok': 'بانكوك',
  'Ankara': 'أنقرة',
  'Ashgabat': 'عشق آباد',
  'Abu Dhabi': 'أبو ظبي',
  'Tashkent': 'طشقند',
  'Hanoi': 'هانوي',
  "Sana'a": 'صنعاء',
  'Tirana': 'تيرانا',
  'Andorra la Vella': 'أندورا لا فيلا',
  'Vienna': 'فيينا',
  'Minsk': 'مينسك',
  'Brussels': 'بروكسل',
  'Sarajevo': 'سراييفو',
  'Sofia': 'صوفيا',
  'Zagreb': 'زغرب',
  'Prague': 'براغ',
  'Copenhagen': 'كوبنهاغن',
  'Tallinn': 'تالين',
  'Helsinki': 'هلسنكي',
  'Paris': 'باريس',
  'Berlin': 'برلين',
  'Athens': 'أثينا',
  'Budapest': 'بودابست',
  'Reykjavik': 'ريكيافيك',
  'Dublin': 'دبلن',
  'Rome': 'روما',
  'Pristina': 'بريشتينا',
  'Riga': 'ريغا',
  'Vaduz': 'فادوز',
  'Vilnius': 'فيلنيوس',
  'Luxembourg': 'لوكسمبورغ',
  'Valletta': 'فاليتا',
  'Chisinau': 'كيشيناو',
  'Monaco': 'موناكو',
  'Podgorica': 'بودغوريتسا',
  'Amsterdam': 'أمستردام',
  'Skopje': 'إسكوبية',
  'Oslo': 'أوسلو',
  'Warsaw': 'وارسو',
  'Lisbon': 'لشبونة',
  'Bucharest': 'بوخارست',
  'San Marino': 'سان مارينو',
  'Belgrade': 'بلغراد',
  'Bratislava': 'براتيسلافا',
  'Ljubljana': 'ليوبليانا',
  'Madrid': 'مدريد',
  'Stockholm': 'ستوكهولم',
  'Bern': 'برن',
  'Kyiv': 'كييف',
  'London': 'لندن',
  'Vatican City': 'الفاتيكان',
  "St. John's": 'سانت جونز',
  'Buenos Aires': 'بوينس آيرس',
  'Nassau': 'ناساو',
  'Bridgetown': 'بريدج تاون',
  'Belmopan': 'بلموبان',
  'Sucre': 'سوكري',
  'Brasília': 'برازيليا',
  'Ottawa': 'أوتاوا',
  'Santiago': 'سانتياغو',
  'Bogotá': 'بوغوتا',
  'San José': 'سان خوسيه',
  'Havana': 'هافانا',
  'Roseau': 'روسو',
  'Santo Domingo': 'سانتو دومينغو',
  'Quito': 'كيتو',
  'San Salvador': 'سان سلفادور',
  'Palikir': 'باليكير',
  'Suva': 'سوفا',
  "St. George's": 'سانت جورجز',
  'Guatemala City': 'غواتيمالا',
  'Georgetown': 'جورج تاون',
  'Port-au-Prince': 'بورت أو برنس',
  'Tegucigalpa': 'تيغوسيغالبا',
  'Kingston': 'كينغستون',
  'Tarawa': 'تاراوا',
  'Majuro': 'ماجورو',
  'Mexico City': 'مكسيكو سيتي',
  'Managua': 'ماناغوا',
  'Ngerulmud': 'نغيرولمود',
  'Panama City': 'بنما سيتي',
  'Port Moresby': 'بورت مورسبي',
  'Asunción': 'أسونسيون',
  'Lima': 'ليما',
  'Basseterre': 'باستير',
  'Castries': 'كاستري',
  'Kingstown': 'كينغستاون',
  'Apia': 'أبيا',
  'Honiara': 'هونيارا',
  'Paramaribo': 'باراماريبو',
  "Nuku'alofa": 'نوكو ألوفا',
  'Port of Spain': 'بورت أوف سبين',
  'Funafuti': 'فونافوتي',
  'Washington, D.C.': 'واشنطن العاصمة',
  'Montevideo': 'مونتيفيديو',
  'Port Vila': 'بورت فيلا',
  'Caracas': 'كاراكاس',
  'Canberra': 'كانبرا',
  'Wellington': 'ويلينغتون',
  'Avarua': 'أفاروا',
  'Alofi': 'ألوفي',
  'Hamilton': 'هاميلتون',
  'Gustavia': 'غوستافيا',
  'Marigot': 'ماريغو',
  'Saint-Pierre': 'سان بيير',
  'Mata-Utu': 'ماتا أوتو',
  'Adamstown': 'آدمزتاون',
  'Stanley': 'ستانلي',
  'King Edward Point': 'نقطة الملك إدوارد',
  'Longyearbyen': 'لونغياربين',
  'Tórshavn': 'تورسهافن',
  'Gibraltar': 'جبل طارق',
  'Nuuk': 'نوك',
  'Cockburn Town': 'كوكبرن تاون',
  'Douglas': 'دوغلاس',
  'Saint Helier': 'سانت هيلير',
  'Plymouth': 'بليموث',
  'Brades': 'براديس',
  'Little Rock': 'ليتل روك',
  'George Town': 'جورج تاون',
  'Hagåtña': 'هاغاتنيا',
  'Saipan': 'سايبان',
  'San Juan': 'سان خوان',
  'Charlotte Amalie': 'شارلوت أمالي',
  'Road Town': 'رود تاون',
  'Oranjestad': 'أورانياستاد',
  'Philipsburg': 'فيليبسبرغ',
  'The Valley': 'ذا فالي',
  'Basse-Terre': 'باس تير',
  'Fort-de-France': 'فور دو فرانس',
  'Cayenne': 'كايين',
  'Papeete': 'بابيتي',
  'Nouméa': 'نوميا',
};

function localizeCountry(country, lang) {
  const localized = country.toObject ? country.toObject() : { ...country };

  if (country.name === 'Israel') {
    localized.name = lang === 'ar' ? 'إسرائيل (النظام القمعي)' : 'Israel (oppressive regime)';
  }

  if (lang !== 'ar') return localized;

  const countryJson = loadArabicData();
  const countryName = country.name;

  const localize = (value, map) => {
    if (!value) return value;
    return map[value] || value;
  };

  const localizeArray = (arr, map) => {
    if (!arr || !Array.isArray(arr)) return arr;
    return arr.map(item => map[item] || item);
  };

  localized.name = countryJson[countryName] || countryName;
  if (localized.name === 'إسرائيل' || localized.name === 'Israel') {
    localized.name = 'إسرائيل (النظام القمعي)';
  }
  localized.capital = capitalMap[country.capital] || country.capital;
  localized.continent = continentMap[country.continent] || country.continent;
  localized.currency = currencyMap[country.currency] || country.currency;
  localized.languages = localizeArray(country.languages, languageMap);
  localized.climate = climateMap[country.climate] || country.climate;
  localized.government = governmentMap[country.government] || country.government;
  localized.timezone = localizeArray(country.timezone, timezoneMap);

  if (country.independence) {
    try {
      const date = new Date(country.independence);
      if (!isNaN(date.getTime())) {
        localized.independence = date.toLocaleDateString('ar-SA', {
          year: 'numeric', month: 'long', day: 'numeric'
        });
      }
    } catch {}
  }

  if (country.nationalDay) {
    try {
      const date = new Date(country.nationalDay);
      if (!isNaN(date.getTime())) {
        localized.nationalDay = date.toLocaleDateString('ar-SA', {
          month: 'long', day: 'numeric'
        });
      }
    } catch {}
  }

  if (country.geographicLocation?.borders && Array.isArray(country.geographicLocation.borders)) {
    localized.geographicLocation = {
      ...(localized.geographicLocation || {}),
      borders: country.geographicLocation.borders.map(b => borderCodeMap[b] || b),
    };
  }

  if (country.religions && Array.isArray(country.religions)) {
    localized.religions = country.religions.map(r => ({
      ...r.toObject ? r.toObject() : r,
      name: religionMap[r.name] || r.name,
    }));
  }

  if (country.traditions && Array.isArray(country.traditions)) {
    localized.traditions = country.traditions.map(t => ({
      ...t.toObject ? t.toObject() : t,
      category: traditionCategoryMap[t.category] || t.category,
    }));
  }

   if (country.touristAttractions && Array.isArray(country.touristAttractions)) {
     localized.touristAttractions = country.touristAttractions.map(a => {
       const attraction = a.toObject ? a.toObject() : a;
       return {
         ...attraction,
         name: attraction.name, // Keep original name for fallback
         description: attraction.description, // Keep original description for fallback
         location: attraction.location, // Keep original location for fallback
         category: attractionCategoryMap[attraction.category] || attraction.category,
       };
     });
   }

  return localized;
}

module.exports = { localizeCountry };
